// This file was generated by the XState CLI, please do not edit it manually.
import { assign, createMachine } from 'xstate';

const machine = createMachine(
  {
    context: {
      count: 0,
    },
    id: 'Counter',
    initial: 'idle',
    states: {
      idle: {
        on: {
          add: [
            {
              target: 'idle at a higher place',
              guard: ({ context }) => context.count >= 5,
              actions: assign({ count: 1000 }),
            },
            {
              target: 'idle',
              actions: assign({ count: ({ context }) => context.count + 1 }),
            },
          ],
          reset: {
            target: 'idle',
            actions: assign({ count: 0 }),
          },
        },
      },
      'idle at a higher place': {
        on: {
          add: {
            target: 'idle at a higher place',
            actions: assign({ count: ({ context }) => context.count + 10 }),
          },
          reset: {
            target: 'idle',
            actions: assign({ count: 0 }),
          },
        },
      },
    },
    types: {
      events: {} as { type: 'add' } | { type: 'reset' },
      context: {} as { count: number },
    },
  },
  {
    actions: {},
    actors: {},
    guards: {},
    delays: {},
  },
);
export const skyConfig = {
  actorId: 'b349528d-57a3-4ab2-ade2-3ea585b1963a',
  machine,
};
